### PR TITLE
bump to 1.0.2

### PR DESCRIPTION
**Pull request by djsutherland**

### CODE REVIEW

**Comment by djsutherland** [comment]
Think the build system changed in the meantime, and the Windows install script doesn't work anymore: e.g.
`
(C:\bld\brotli_1515183498335\_b_env) C:\bld\brotli_1515183498335\work\brotli-1.0.2\build_static_Release>move "C:\bld\brotli_1515183498335\work\brotli-1.0.2\include\brotli\*" "C:\bld\brotli_1515183498335\_b_env\Library\include\brotli\"`
`The system cannot find the path specified.`

Will investigate later.

**Comment by dougalsutherland** [comment]
Just for context on a brief search of what others have done:

- [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/makeheaders/makeheaders-0_p4.ebuild?id=6d3f0053feb20396daf71d11eac21459989a0ac2), the I-think-inherited-from-Gentoo [exherbo](http://git.exherbo.org/summer/packages/dev-util/makeheaders/index.html), and [AUR](https://aur.archlinux.org/packages/makeheaders/) packages use the original source
- Homebrew rejected a PR of a fork because "upstream doesn't really have a release process it seems and this is a fork of an unofficial github repo" (https://github.com/Homebrew/legacy-homebrew/pull/34319#issuecomment-63810246)

Didn't see any other packages of it.

@rowanthorpe, do you have opinions on this? If you wanted to call your fork `makeheaders-rt` or whatever and tag a release, then that would remove any doubt about packaging it. If you don't want to do that, maybe we can get an opinion from others on conda-forge about the best option here.

**Comment by djsutherland** [comment]
@conda-forge/brotli, this works on Windows now.

**Review by CJ-Wright — APPROVED** [review]
LGTM (although I would wait for more windows savvy reviewers)

**Comment by djsutherland** [comment]
Hmm. I just noticed that the initial build, with `DBUILD_SHARED_LIBS:BOOL=ON`, actually also installs `brotli{enc,dec,common}-static`:

```
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlienc.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/bin/brotlienc.dll
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlidec.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/bin/brotlidec.dll
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlicommon.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/bin/brotlicommon.dll
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlienc-static.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlidec-static.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlicommon-static.lib
```
And then the second build, with `-DBUILD_SHARED_LIBS:BOOL=OFF`, installs
```
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/bin/brotli.exe
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlienc_static.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/bin/brotlienc_static.dll
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlidec_static.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/bin/brotlidec_static.dll
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlicommon_static.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/bin/brotlicommon_static.dll
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlienc-static_static.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlidec-static_static.lib
-- Installing: C:/bld/brotli_1517194842499/_b_env/Library/lib/brotlicommon-static_static.lib
```
This seems dumb.

Also, looking at [the `CMakeLists`](https://github.com/google/brotli/blob/master/CMakeLists.txt) and [the documentation](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html), I think that the second build is actually not doing *anything* differently than the first one, since its `add_library` calls all explicitly set `SHARED` or `STATIC`. Going to remove the second build since I think it's identical. This means that the package will ship `brotlienc-static.lib` instead of `brotlienc_static.lib`, but since that's the choice made by the package developers that seems preferable. There also won't be a `brotli_static.exe` anymore, but I think the previous one wasn't actually statically linked anyway, and I don't know why you'd really care for the `.exe` in any case.

**Comment by djsutherland** [comment]
@conda-forge/brotli I changed the Unix build to only build once also, because the cmake build files now explicitly specify to build both static and dynamic libs. Passing on all platforms now (skipped AppVeyor on the last because it didn't change, but passing build [on the previous](https://ci.appveyor.com/project/conda-forge/brotli-feedstock/build/1.0.22)) and ready for review/merge. :)

**Review by xhochy — APPROVED** [review]

**Pull request merged**
