### PR TITLE
add build for the python bindings

### LINKED ISSUE #26: Build the python bindings?
Should we as a subpackage build the python bindings that are found on https://pypi.org/project/Brotli/#files ?

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
@xhochy This is now ready for review

**Comment by isuruf** [comment]
Is this the same as `brotlipy`?

**Comment by xhochy** [comment]
> Is this the same as `brotlipy`?

No, brotlipy is a different package originating from https://github.com/python-hyper/brotlipy/

**Comment by mariusvniekerk** [comment]
Thanks @xhochy

**Pull request merged**
